dist: trusty
sudo: required
env:
  global:
    - DISPLAY=:99.0
    - PYTEST_ADDOPTS="--verbose --instafail"
    - FF_LEGACY_BINARY=/usr/local/bin/firefox
matrix:
  include:
    - language: python
      python: 2.7
      env: CHROME=1 TOXENV=py27-chrome --trace
      addons:
        apt:
          packages:
            - google-chrome-stable
    - language: ruby
      rvm: 2.3.3
      jdk: oraclejdk8
      env: CHROME=1 TASK=//rb:chrome-test
      addons:
        apt:
          packages:
            - google-chrome-stable
  fast_finish: true
  # allow_failures:
  #   - env: TASK="calcdeps //javascript/webdriver:webdriver-firefox:run"
  #   - env: CHROME=1 TASK=//java/client/test/com/thoughtworks/selenium:chrome-rc-test:run
  #   - env: TASK=//java/client/test/com/thoughtworks/selenium:firefox-rc-test:run
  #   - env: TOXENV=py27-firefox
  #   - env: MARIONETTE=1 TOXENV=py27-marionette
  #   - env: TOXENV=py27-remote
  #   - env: TOXENV=py36-firefox
  #   - env: MARIONETTE=1 TOXENV=py36-marionette
  #   - env: TOXENV=py36-remote
  #   - env: PHANTOMJS=1 TASK=//rb:remote-phantomjs-test
  #   - env: TASK=//rb:docs
before_install: ./scripts/travis/before_install.sh
install: ./scripts/travis/install.sh
before_script: ./scripts/travis/before_script.sh
script: ./scripts/travis/script.sh
notifications:
  email: false
  irc:
    channels:
      - secure: K+Wuro8Y/66zt9truTZuZzFmPqiGrFsH/sPzOBDK3+57mL6/vg2NoQCXOTq3U5RLdVKavlvZcm6+9nsNncVPRgzL7ORuW3BgLaBJis3lTA13AqlOnAbXcYytQEulVeWmvPipHFFFqaHs/z77lxm4fKwAAuBnK1f+mXKZDZR2hLo=
    on_success: never
    on_failure: always
    use_notice: true
    skip_join: true
