dist: trusty
sudo: required
env:
  global:
    - DISPLAY=:99.0
    - PYTEST_ADDOPTS="--verbose --instafail"
    - FF_ESR_BINARY=$HOME/firefox-latest-esr/firefox/firefox-bin
    - FF_NIGHTLY_BINARY=$HOME/firefox-latest-nightly/firefox/firefox-bin
git:
  depth: 10

_bindings:
  java: &java
    language: java
    jdk: oraclejdk8
  python: &python
    language: python
    python: "2.7"
  ruby: &ruby
    language: ruby
    rvm: 2.0.0-p648
    jdk: oraclejdk8

_browsers:
  firefox: &firefox-latest
    addons:
      firefox: latest
  firefox-esr: &firefox-esr
    addons:
      firefox: latest-esr
  firefox-nightly: &firefox-nightly
    addons:
      firefox: latest-nightly
  chrome: &chrome
    addons:
      apt:
        packages:
          - google-chrome-stable

cache:
  directories:
    - buck-out
    - build

matrix:
  exclude:
    - env: BUCK="//javascript/atoms:atoms //javascript/webdriver:all_js //javascript/ie-driver:atoms //javascript/chrome-driver:atoms //javascript/android-atoms:atoms ios_driver"
      <<: *java
    - env: CHROME=1 BUCK="test chrome-test"
      <<: *java
      <<: *chrome
    - env: TOXENV=flake8
      <<: *python
    - env: TOXENV=docs
      <<: *python
    - env: CHROME=1 TOXENV=py27-chrome
      <<: *python
      <<: *chrome
    - env: TOXENV=py27-firefox
      <<: *python
      <<: *firefox-esr
    - env: TOXENV=py27-remote
      <<: *python
      <<: *firefox-nightly
    - env: MARIONETTE=1 TOXENV=py27-marionette
      <<: *python
      <<: *firefox-nightly
  include:
    - env: MARIONETTE=1 TOXENV=py36-remote
      <<: *python
      <<: *firefox-esr
      python: 3.6
before_install: ./scripts/travis/before_install.sh
install: ./scripts/travis/install.sh
before_script: ./scripts/travis/before_script.sh
script: travis_wait ./scripts/travis/script.sh

notifications:
  email: false
  irc:
    channels:
      - secure: K+Wuro8Y/66zt9truTZuZzFmPqiGrFsH/sPzOBDK3+57mL6/vg2NoQCXOTq3U5RLdVKavlvZcm6+9nsNncVPRgzL7ORuW3BgLaBJis3lTA13AqlOnAbXcYytQEulVeWmvPipHFFFqaHs/z77lxm4fKwAAuBnK1f+mXKZDZR2hLo=
    on_success: never
    on_failure: always
    use_notice: true
    skip_join: true
