sudo: required
env:
  global:
    - DISPLAY=:99.0
    - PYTEST_ADDOPTS="--verbose --instafail"
    - FF_LEGACY_BINARY=/usr/local/bin/firefox
matrix:
  include:
    - language: python
      python: 2.7
      env: CHROME=1 TOXENV=py27-chrome
    - language: python
      python: 3.5
      env: CHROME=1 TOXENV=py35-chrome
  fast_finish: true
before_install: ./scripts/travis/before_install.sh
install: ./scripts/travis/install.sh
before_script: ./scripts/travis/before_script.sh
script: ./scripts/travis/script.sh
notifications:
  email: false
  irc:
    channels:
      - secure: K+Wuro8Y/66zt9truTZuZzFmPqiGrFsH/sPzOBDK3+57mL6/vg2NoQCXOTq3U5RLdVKavlvZcm6+9nsNncVPRgzL7ORuW3BgLaBJis3lTA13AqlOnAbXcYytQEulVeWmvPipHFFFqaHs/z77lxm4fKwAAuBnK1f+mXKZDZR2hLo=
    on_success: never
    on_failure: always
    use_notice: true
    skip_join: true
