dist: trusty
sudo: required
env:
  global:
    - DISPLAY=:99.0
    - PYTEST_ADDOPTS="--verbose --instafail"
    - FF_ESR_BINARY=$HOME/firefox-latest-esr/firefox/firefox-bin
    - FF_NIGHTLY_BINARY=$HOME/firefox-latest-nightly/firefox/firefox-bin
matrix:
  exclude:
    - language: java
      jdk: oraclejdk8
      env: CHROME=1 TASK="calcdeps //javascript/atoms:atoms-chrome:run"
      addons:
        apt:
          packages:
            - google-chrome-stable
    - language: java
      jdk: oraclejdk8
      env: MARIONETTE=1 TASK=//java/client/test/com/thoughtworks/selenium:firefox-rc-test:run
      addons:
        firefox: latest-nightly
    - language: java
      jdk: oraclejdk8
      env: CHROME=1 TASK=//java/client/test/com/thoughtworks/selenium:chrome-rc-test:run
      addons:
        apt:
          packages:
            - google-chrome-stable
    - language: java
      jdk: oraclejdk8
      env: CHROME=1 TASK=test_chrome
      addons:
        apt:
          packages:
            - google-chrome-stable
    - language: python
      python: 2.7
      env: MARIONETTE=1 TOXENV=py27-marionette
      addons:
        firefox: latest-nightly
    - language: python
      python: 3.6
      env: MARIONETTE=1 TOXENV=py36-marionette
      addons:
        firefox: latest-nightly
  include:
    - language: python
      python: 2.7
      env: CHROME=1 TOXENV=py27-chrome
      addons:
        apt:
          packages:
            - google-chrome-stable
    - language: python
      python: 3.6
      env: CHROME=1 TOXENV=py36-chrome
      addons:
        apt:
          packages:
            - google-chrome-stable
  fast_finish: true
before_install: ./scripts/travis/before_install.sh
install: ./scripts/travis/install.sh
before_script: ./scripts/travis/before_script.sh
script: ./scripts/travis/script.sh
notifications:
  email: false
  irc:
    channels:
      - secure: K+Wuro8Y/66zt9truTZuZzFmPqiGrFsH/sPzOBDK3+57mL6/vg2NoQCXOTq3U5RLdVKavlvZcm6+9nsNncVPRgzL7ORuW3BgLaBJis3lTA13AqlOnAbXcYytQEulVeWmvPipHFFFqaHs/z77lxm4fKwAAuBnK1f+mXKZDZR2hLo=
    on_success: never
    on_failure: always
    use_notice: true
    skip_join: true
